const years = [
  {
    title: "First Year",
    description:
      "Foundation in mathematics, programming fundamentals, and basic engineering principles.",
    semester01: "Semester 01:",
    semester02: "Semester 02:",
    subjectsS01: [
      "Analysis 01",
      "Algebra 01",
      "Algorithms and data structure 01",
      "Structure machine 01",
      "Chemistry 01",
      "Physics 01",
      "Introduction to Web Development",
      "Technical English",
      "Professional communication",
      "Project management",
    ],

    subjectsS02: [
      "Analysis 02",
      "Algebra 02",
      "Algorithms and data structure 02",
      "Structure machine 02",
      "Chemistry 02",
      "Physics 02",
      "Programming 02",
      "Probability and statistics 01",
      "Ethics and professional conduct",
      "English for Automation and Control",
      "Interpersonal Communication",
      "Project management",
    ],
  },
  {
    title: "Second Year",
    description:
      "Advanced programming concepts and introduction to automation systems.",
    semester01: "Semester 03:",
    semester02: "Semester 04:",
    subjectsS01: [
      "Information systems",
      "Files and data structure",
      "Signal Theory",
      "Graph theory",
      "Algorithms and data structure 03",
      "Electricity 01",
      "General electronics 01",
      "Programming 03",
      "Numerical methods",
      "English for Technical Communication 01",
      "Industrial automated system",
    ],
    subjectsS02: [
      "Electrical installations",
      "English for Technical Communication 02",
      "Introduction to Artificial Intelligence",
      "Computer Networks 01",
      "Object oriented programming",
      "Main Functions of Electronics",
      "Combinatorial and sequential logic",
      "Signal Processing",
      "Servo Systems 01",
      "Software engineering",
      "Databases",
      "Operating system",
      "Networks and telecommunications",
    ],
  },
  {
    title: "Third Year",
    description:
      "Specialized courses in computer science and automation engineering.",
    semester01: "Semester 05:",
    semester02: "Semester 06:",
    subjectsS01: [
      "Innovation management",
      "Robotics",
      "Electrical Machines and Drives",
      "Embedded Computer IMobile and IoT Programming",
      "Database Administration",
      "Industrial Programmable Automation",
      "Industrial Sensors and Instrumentation",
      "Power Electronics",
      "Servo Systems 02",
      "Computer Security",
      "DevOps, CI/CD development methods",
      "Decision support system",
      "Data analysis",
    ],
    subjectsS02: [
      "Machine Learning",
      "IT project management",
      "Operational Research",
      "AI Techniques",
      "Industrial Actuators",
      "Embedded Calculator 02",
      "Industrial Programmable Automation 02",
      "Supervision and HMI",
      "End of Cycle Project",
      "Electrical Standards and Safety",
      "Entrepreneurship and Business Management",
      "Cloud Computing et visualisation",
    ],
  },
];

export default years;
